export function getMockDataWebpackAlias(tenantId: string): string | null;
export function getDataAdapter(tenantId: string): "mock" | "strapi";
export function usesMockData(tenantId: string): boolean;
export function getMockDataFolder(tenantId: string): string;
export function getMockDataTsconfigPaths(tenantId: string): { base: string; glob: string };
export function readMockMap(): Record<string, string>;
export const repoRoot: string;
export const tenantsDir: string;
export const mockMapPath: string;
export const mockDataStubRel: string;
